name: "Pa11y Ratchet"
author: "Nathan Arthur"
branding:
  icon: "check"
  color: "green"
description: "Fail if Pa11y detects newly-introduced accessibility issues"
inputs:
  sitemap-url:
    description: "The sitemap URL to test"
    required: true
  github-token:
    description: "The GitHub token for the repository"
    required: true
  find:
    description: "The URL substring to search for in sitemap URLs"
    required: false
  replace:
    description: "The replacement string for the find string"
    required: false
  include:
    description: "Only include URLs that match this regular expression"
    required: false
  ignore:
    description: "A comma-seperated list of codes of issues to ignore"
    required: false
  config-path:
    description: "Path to a pa11y configuration file"
    required: false
runs:
  using: "composite"
  steps:
    - name: Enable unprivileged user namespaces
      run: sudo sysctl kernel.unprivileged_userns_clone=1
      shell: bash
    - uses: actions/setup-node@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - run: pnpm install
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: pnpm run build
      shell: bash
      working-directory: ${{ github.action_path }}
    - uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: await import("${{ github.action_path }}/index.js")
      env:
        SITEMAP_URL: ${{ inputs.sitemap-url }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        FIND: ${{ inputs.find }}
        REPLACE: ${{ inputs.replace }}
        INCLUDE: ${{ inputs.include }}
        IGNORE: ${{ inputs.ignore }}
        CONFIG_PATH: ${{ inputs.config-path }}
