name: "Pa11y Ratchet"
description: "Fail if Pa11y detects newly-introduced accessibility issues"
inputs:
  sitemap-url:
    description: "The sitemap URL to test"
    required: true
  github-token:
    description: "The GitHub token for the repository"
    required: true
  find:
    description: "The URL substring to search for in sitemap URLs"
    required: false
  replace:
    description: "The replacement string for the find string"
    required: false
  include:
    description: "Only include URLs that match this regular expression"
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - run: pnpm install --prod
      shell: bash
    - run: node ./dist/index.js
      shell: bash
      with:
        sitemap-url: ${{ inputs.sitemap-url }}
        github-token: ${{ inputs.github-token }}
        find: ${{ inputs.find }}
        replace: ${{ inputs.replace }}
        include: ${{ inputs.include }}
