name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  check-version:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Get base package.json
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3.raw" \
               -o base-package.json \
               "https://api.github.com/repos/${{ github.repository }}/contents/package.json?ref=${{ github.base_ref }}"
      - name: Compare versions
        run: |
          BASE_VERSION=$(node -p "require('./base-package.json').version")
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          if [ "$BASE_VERSION" == "$CURRENT_VERSION" ]; then
            echo "Error: Version in package.json must be updated"
            exit 1
          fi
          echo "Version changed from $BASE_VERSION to $CURRENT_VERSION"
  run-action:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm install
      - run: pnpm run build
      - uses: ./
        with:
          sitemap-url: https://pinepeakdigital.com/sitemap-0.xml
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore: WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.InputEmail.Name
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm install
      - run: pnpm run test
  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm install
      - run: pnpm run checkTs
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm install
      - run: pnpm run lint
